# jupyter notebook高级命令 魔法命令

## %run

In [3]:
%run myscript/hello.py

hello Machine Learning !


## %timeit

In [4]:
%timeit L = [i ** 2 for i in range(1000)]

391 µs ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%timeit L = [i ** 2 for i in range(1000000)]

422 ms ± 12.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

669 µs ± 128 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## %time

In [8]:
%time L = [i ** 2 for i in range(1000)]

CPU times: user 594 µs, sys: 6 µs, total: 600 µs
Wall time: 775 µs


# 其他魔法命令

In [9]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

# numy基础
## numpy.array 基础

In [10]:
import numpy
numpy.__version__

'1.15.1'

In [11]:
import numpy as np

nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
nparr[5]

5

In [13]:
nparr[1] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [14]:
nparr.dtype

dtype('int64')

In [15]:
nparr[3] = 3.14

In [16]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr.dtype

dtype('int64')

In [19]:
nparr3 = np.array([0, 1, 2, 3.0])
nparr3

array([0., 1., 2., 3.])

In [20]:
nparr3.dtype

dtype('float64')

## 其他创建numpy.array的方法

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10).dtype

dtype('float64')

In [23]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [28]:
np.full(shape=(3, 5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [29]:
np.full(shape=(3, 5), fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

## arange

In [30]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [31]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
np.arange(0, 20, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

In [34]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [36]:
# 0-20 以相等步长截取10个 包含头尾
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [38]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [39]:
# 前闭后开
np.random.randint(0, 10)

8

In [40]:
np.random.randint(0, 10, 10)

array([9, 3, 3, 9, 6, 4, 9, 4, 6, 2])

In [41]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.random.randint(4, 8, size=10)

array([4, 5, 4, 6, 5, 5, 7, 6, 7, 7])

In [43]:
np.random.randint(4, 8, size=(3, 5))

array([[7, 6, 5, 6, 4],
       [5, 7, 4, 6, 5],
       [6, 6, 4, 5, 6]])

In [44]:
# 随机种子
np.random.seed(888)
np.random.randint(4, 8, size=(3, 5))

array([[6, 6, 5, 7, 6],
       [7, 7, 6, 5, 4],
       [5, 5, 4, 5, 4]])

In [46]:
np.random.seed(888)
np.random.randint(4, 8, size=(3, 5))

array([[6, 6, 5, 7, 6],
       [7, 7, 6, 5, 4],
       [5, 5, 4, 5, 4]])

In [47]:
np.random.random()

0.41109939763659853

In [48]:
np.random.random(10)

array([0.86383856, 0.72591233, 0.1906744 , 0.43201955, 0.07735013,
       0.48788075, 0.3952319 , 0.90862117, 0.03677048, 0.84336868])

In [49]:
np.random.random((3, 5))

array([[0.82231207, 0.50290164, 0.58799622, 0.53384032, 0.0449182 ],
       [0.06740007, 0.82223191, 0.57353791, 0.42893951, 0.09928623],
       [0.05974346, 0.12334144, 0.61528083, 0.02959695, 0.16609596]])

In [50]:
# 符合正态分布的
np.random.normal()

0.9879964052314433

In [56]:
np.random.normal(loc=10, scale=100)

34.70955924344875

In [53]:
np.random.normal(0, 1, (3, 5))

array([[-1.36037345, -2.17752387, -0.18071875, -1.14137536, -1.6673638 ],
       [-0.09037666, -0.12645462,  0.67487848,  0.18847641,  0.75658671],
       [-0.267414  ,  0.3533793 , -0.08355021,  0.05846058, -0.68915711]])

In [54]:
np.random.normal?

In [57]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

## Numpy.array的基本操作

In [58]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# 一维转二维
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [60]:
# 几维
x.ndim

1

In [61]:
X.ndim

2

In [62]:
x.shape

(10,)

In [63]:
X.shape

(3, 5)

In [64]:
x.size

10

In [65]:
X.size

15

### numpy.array的数据访问

In [66]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x[0]

0

In [68]:
x[-1]

9

In [72]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
# 不推荐
X[0][0]

0

In [71]:
X[0,0]

0

In [74]:
x[0:5]

array([0, 1, 2, 3, 4])

In [77]:
x[:5]

array([0, 1, 2, 3, 4])

In [78]:
x[5:]

array([5, 6, 7, 8, 9])

In [76]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
x[::2]

array([0, 2, 4, 6, 8])

In [80]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [81]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [82]:
# 等同X[:2]
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [84]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [85]:
X[0]

array([0, 1, 2, 3, 4])

In [86]:
X[0, ::]

array([0, 1, 2, 3, 4])

In [89]:
X[0, :].ndim

1

In [88]:
X[0].ndim

1

In [90]:
X[:, 0]

array([ 0,  5, 10])

In [91]:
# 子矩阵是对原矩阵的引用
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [92]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [93]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [94]:
subX2 = X[:2, :3].copy()
subX2

array([[100,   1,   2],
       [  5,   6,   7]])

In [96]:
subX2[0, 0] = 111
subX2

array([[111,   1,   2],
       [  5,   6,   7]])

In [97]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

### Reshape

In [98]:
x.shape

(10,)

In [99]:
x.ndim

1

In [102]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [103]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
x.ndim

1

In [105]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [106]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [107]:
B.ndim

2

In [108]:
B.shape

(1, 10)

In [109]:
x.shape

(10,)

In [110]:
# 改成10行, 列不考虑
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [111]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [112]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [113]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

### 合并操作

In [114]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [115]:
x

array([1, 2, 3])

In [116]:
y

array([3, 2, 1])

In [117]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [118]:
z = np.array([666, 666, 666])

In [119]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [120]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [121]:
# 默认axis=0 沿着行拼接
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [123]:
# axis=1 沿着列拼接
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [125]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions

In [126]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [127]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [128]:
np.vstack([z, A])

array([[666, 666, 666],
       [  1,   2,   3],
       [  4,   5,   6]])

In [130]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [132]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [133]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

### 分割操作

In [135]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
x1, x2, x3 = np.split(x, [3, 7])

In [137]:
x1

array([0, 1, 2])

In [138]:
x2

array([3, 4, 5, 6])

In [139]:
x3

array([7, 8, 9])

In [140]:
x1, x2 = np.split(x, [5])

In [141]:
x1 

array([0, 1, 2, 3, 4])

In [142]:
x2

array([5, 6, 7, 8, 9])

In [143]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [144]:
A1, A2 = np.split(A, [2])

In [145]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [146]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [147]:
A3, A4 = np.split(A, [2], axis=1)

In [148]:
A3

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [149]:
A4

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [151]:
upper, lower = np.vsplit(A, [1])

In [152]:
upper

array([[0, 1, 2, 3]])

In [153]:
lower

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [154]:
left, right = np.hsplit(A, [2])

In [155]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [156]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [157]:
X, y = np.hsplit(A, [-1])

In [158]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [161]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [162]:
y.reshape(1, -1)

array([[ 3,  7, 11, 15]])

In [160]:
A[:, -1]

array([ 3,  7, 11, 15])

### numpy.array运算

给定一个向量, 让向量中每一个数乘2

a = (0, 1, 2)

a * 2 = (0, 2, 4)

In [186]:
n = 1000000
L = [i for i in range(n)]
L

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [166]:
L * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [172]:
%%time
A = []
for l in L:
    A.append(2*l)

CPU times: user 259 ms, sys: 32.6 ms, total: 292 ms
Wall time: 299 ms


In [173]:
%%time
A = [2*l for l in L]

CPU times: user 130 ms, sys: 47 ms, total: 177 ms
Wall time: 208 ms


In [183]:
%%time
A = np.array(2*l for l in L)

CPU times: user 19.3 ms, sys: 48 ms, total: 67.3 ms
Wall time: 67.4 ms


In [189]:
%%time
L = np.array(L)
A = 2 * L

CPU times: user 108 ms, sys: 73.5 ms, total: 182 ms
Wall time: 200 ms


In [190]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

### Universal Functions

In [191]:
X = np.arange(16).reshape((4, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [192]:
X + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [193]:
X -1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [194]:
X * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [195]:
X / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5],
       [6. , 6.5, 7. , 7.5]])

In [196]:
X // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5],
       [6, 6, 7, 7]])

In [197]:
X ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [198]:
X % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [199]:
1 / X

/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([[       inf, 1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [200]:
np.abs(X)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [201]:
np.sin(X)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [202]:
np.cos(X)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [203]:
np.tan(X)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02],
       [-6.35859929e-01,  4.63021133e-01,  7.24460662e+00,
        -8.55993401e-01]])

In [205]:
np.arctan(X)

array([[0.        , 0.78539816, 1.10714872, 1.24904577],
       [1.32581766, 1.37340077, 1.40564765, 1.42889927],
       [1.44644133, 1.46013911, 1.47112767, 1.48013644],
       [1.48765509, 1.49402444, 1.49948886, 1.50422816]])

In [206]:
# e的X次方
np.exp(X)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [207]:
# 3的X次方
np.power(3, X)

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]])

In [208]:
3 ** X

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]])

In [209]:
np.log(X)

/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [210]:
np.log2(X)

/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log2
  if __name__ == '__main__':


array([[      -inf, 0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 , 2.80735492],
       [3.        , 3.169925  , 3.32192809, 3.45943162],
       [3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [211]:
np.log10(X)

/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log10
  if __name__ == '__main__':


array([[      -inf, 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵运算

In [212]:
A = np.arange(4).reshape((2, 2))
A

array([[0, 1],
       [2, 3]])

In [214]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [215]:
A + B

array([[10, 11],
       [12, 13]])

In [216]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [217]:
# 并不是数学上的乘法
A * B

array([[ 0, 10],
       [20, 30]])

In [218]:
# 矩阵乘法
A.dot(B)

array([[10, 10],
       [50, 50]])

In [219]:
A

array([[0, 1],
       [2, 3]])

In [220]:
# 矩阵的转置
A.T

array([[0, 2],
       [1, 3]])

### 向量和矩阵的运算

In [221]:
v = np.array([1, 2])

In [222]:
A

array([[0, 1],
       [2, 3]])

In [223]:
v + A

array([[1, 3],
       [3, 5]])

In [224]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [225]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [227]:
# 行向量堆叠2次 列向量堆叠1次
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [228]:
v

array([1, 2])

In [229]:
A

array([[0, 1],
       [2, 3]])

In [230]:
v * A

array([[0, 2],
       [2, 6]])

In [231]:
v.dot(A)

array([4, 7])

In [232]:
A.dot(v)

array([2, 8])

### 矩阵的逆

In [233]:
A

array([[0, 1],
       [2, 3]])

In [236]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [237]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [239]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [241]:
X = np.arange(16).reshape((2, 8))
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [242]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [244]:
# 伪逆矩阵
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [245]:
pinvX.shape

(8, 2)

In [246]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

### 聚合操作

In [249]:
L = np.random.random(100)
L

array([0.19954226, 0.69903331, 0.4112263 , 0.5719046 , 0.05968078,
       0.15717742, 0.84968636, 0.75512105, 0.80694554, 0.02656121,
       0.88973357, 0.57421841, 0.42468435, 0.32069898, 0.84064519,
       0.74389014, 0.76291234, 0.57398552, 0.18868544, 0.02728358,
       0.03968006, 0.06438226, 0.88929718, 0.69820318, 0.05880488,
       0.63846351, 0.63404067, 0.35449682, 0.85815721, 0.96104591,
       0.35370495, 0.80046664, 0.12234754, 0.24998149, 0.11439854,
       0.05713016, 0.85119634, 0.1127269 , 0.24193509, 0.31289846,
       0.46973484, 0.99164177, 0.86227117, 0.55579007, 0.58199259,
       0.0375603 , 0.07096333, 0.63312178, 0.23924156, 0.48586303,
       0.60264941, 0.73112782, 0.81835343, 0.78675653, 0.6397573 ,
       0.79370622, 0.03793465, 0.25676137, 0.37969158, 0.13628076,
       0.01461544, 0.53429261, 0.90069725, 0.34957684, 0.23772533,
       0.91270257, 0.01829349, 0.37347618, 0.36773871, 0.65002306,
       0.08203894, 0.7302385 , 0.28769415, 0.79031654, 0.76532

In [262]:
# 求和
big_array = np.random.rand(10000000)
%timeit sum(big_array)

1.31 s ± 331 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [263]:
%timeit np.sum(big_array)

6.77 ms ± 494 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [264]:
np.min(big_array)

1.1440846603427701e-07

In [265]:
np.max(big_array)

0.9999999861213674

In [266]:
big_array.max()

0.9999999861213674

In [267]:
big_array.min()

1.1440846603427701e-07

In [268]:
big_array.sum()

5000324.229721862

In [269]:
X = np.arange(16).reshape((4, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [270]:
np.sum(X)

120

In [271]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [272]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [273]:
# 乘
np.prod(X)

0

In [274]:
np.prod(X + 1)

20922789888000

In [275]:
# 均值
np.mean(X)

7.5

In [277]:
# 中位数
np.median(X)

7.5

In [278]:
np.percentile(big_array, 50)

0.5001579310863993

In [279]:
np.median(big_array)

0.5001579310863993

In [280]:
np.percentile(big_array, 100)

0.9999999861213674

In [281]:
np.max(big_array)

0.9999999861213674

In [282]:
# 四分位数
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, percent))

1.1440846603427701e-07
0.24986309510057406
0.5001579310863993
0.7501196668361729
0.9999999861213674


In [283]:
# 方差
np.var(big_array)

0.08337976533897509

In [284]:
# 标准差
np.std(big_array)

0.28875554598825476

In [285]:
x = np.random.normal(0, 1, size=1000000)

In [286]:
np.mean(x)

0.00042056546040972594

In [287]:
np.std(x)

0.9988756001073466

### 索引

In [288]:
np.min(x)

-4.822760461102126

In [289]:
np.argmin(x)

634310

In [290]:
x[634310]

-4.822760461102126

In [291]:
np.argmax(x)

356608

In [292]:
x[356608]

5.122001752914832

In [293]:
np.max(x)

5.122001752914832

### 排序和使用索引

In [294]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [295]:
np.random.shuffle(x)
x

array([ 1,  0, 10,  2,  9, 12, 14,  3, 13, 11,  5, 15,  8,  7,  4,  6])

In [296]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [297]:
x

array([ 1,  0, 10,  2,  9, 12, 14,  3, 13, 11,  5, 15,  8,  7,  4,  6])

In [298]:
x.sort()

In [299]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [300]:
X = np.random.randint(10, size=(4, 4))
X

array([[1, 3, 0, 5],
       [0, 7, 6, 0],
       [4, 7, 0, 2],
       [9, 8, 8, 7]])

In [301]:
np.sort(X)

array([[0, 1, 3, 5],
       [0, 0, 6, 7],
       [0, 2, 4, 7],
       [7, 8, 8, 9]])

In [302]:
np.sort(X, axis=1)

array([[0, 1, 3, 5],
       [0, 0, 6, 7],
       [0, 2, 4, 7],
       [7, 8, 8, 9]])

In [303]:
np.sort(X, axis=0)

array([[0, 3, 0, 0],
       [1, 7, 0, 2],
       [4, 7, 6, 5],
       [9, 8, 8, 7]])

In [304]:
X

array([[1, 3, 0, 5],
       [0, 7, 6, 0],
       [4, 7, 0, 2],
       [9, 8, 8, 7]])

In [305]:
np.random.shuffle(x)

In [306]:
x

array([ 9,  0,  2,  7, 11,  8, 14,  3, 13,  5,  1,  4, 12,  6, 15, 10])

In [307]:
np.argsort(x)

array([ 1, 10,  2,  7, 11,  9, 13,  3,  5,  0, 15,  4, 12,  8,  6, 14])

In [309]:
# 快排标定点
np.partition(x, 3)

array([ 0,  2,  1,  3,  4,  5,  8,  7,  6,  9, 13, 14, 12, 11, 15, 10])

In [310]:
np.argpartition(x, 3)

array([ 1,  2, 10,  7, 11,  9,  5,  3, 13,  0,  8,  6, 12,  4, 14, 15])

In [311]:
X

array([[1, 3, 0, 5],
       [0, 7, 6, 0],
       [4, 7, 0, 2],
       [9, 8, 8, 7]])

In [313]:
np.argsort(X, axis=1)

array([[2, 0, 1, 3],
       [0, 3, 2, 1],
       [2, 3, 0, 1],
       [3, 1, 2, 0]])

In [314]:
np.argpartition(X, 2, axis=1)

array([[2, 0, 1, 3],
       [0, 3, 2, 1],
       [2, 3, 0, 1],
       [3, 1, 2, 0]])