# jupyter notebook高级命令 魔法命令

## %run

In [3]:
%run myscript/hello.py

hello Machine Learning !


## %timeit

In [4]:
%timeit L = [i ** 2 for i in range(1000)]

391 µs ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%timeit L = [i ** 2 for i in range(1000000)]

422 ms ± 12.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

669 µs ± 128 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## %time

In [8]:
%time L = [i ** 2 for i in range(1000)]

CPU times: user 594 µs, sys: 6 µs, total: 600 µs
Wall time: 775 µs


# 其他魔法命令

In [9]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

# numy基础
## numpy.array 基础

In [10]:
import numpy
numpy.__version__

'1.15.1'

In [11]:
import numpy as np

nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
nparr[5]

5

In [13]:
nparr[1] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [14]:
nparr.dtype

dtype('int64')

In [15]:
nparr[3] = 3.14

In [16]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr.dtype

dtype('int64')

In [19]:
nparr3 = np.array([0, 1, 2, 3.0])
nparr3

array([0., 1., 2., 3.])

In [20]:
nparr3.dtype

dtype('float64')

## 其他创建numpy.array的方法

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10).dtype

dtype('float64')

In [23]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [28]:
np.full(shape=(3, 5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [29]:
np.full(shape=(3, 5), fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

## arange

In [30]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [31]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
np.arange(0, 20, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

In [34]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [36]:
# 0-20 以相等步长截取10个 包含头尾
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [38]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [39]:
# 前闭后开
np.random.randint(0, 10)

8

In [40]:
np.random.randint(0, 10, 10)

array([9, 3, 3, 9, 6, 4, 9, 4, 6, 2])

In [41]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.random.randint(4, 8, size=10)

array([4, 5, 4, 6, 5, 5, 7, 6, 7, 7])

In [43]:
np.random.randint(4, 8, size=(3, 5))

array([[7, 6, 5, 6, 4],
       [5, 7, 4, 6, 5],
       [6, 6, 4, 5, 6]])

In [44]:
# 随机种子
np.random.seed(888)
np.random.randint(4, 8, size=(3, 5))

array([[6, 6, 5, 7, 6],
       [7, 7, 6, 5, 4],
       [5, 5, 4, 5, 4]])

In [46]:
np.random.seed(888)
np.random.randint(4, 8, size=(3, 5))

array([[6, 6, 5, 7, 6],
       [7, 7, 6, 5, 4],
       [5, 5, 4, 5, 4]])

In [47]:
np.random.random()

0.41109939763659853

In [48]:
np.random.random(10)

array([0.86383856, 0.72591233, 0.1906744 , 0.43201955, 0.07735013,
       0.48788075, 0.3952319 , 0.90862117, 0.03677048, 0.84336868])

In [49]:
np.random.random((3, 5))

array([[0.82231207, 0.50290164, 0.58799622, 0.53384032, 0.0449182 ],
       [0.06740007, 0.82223191, 0.57353791, 0.42893951, 0.09928623],
       [0.05974346, 0.12334144, 0.61528083, 0.02959695, 0.16609596]])

In [50]:
# 符合正态分布的
np.random.normal()

0.9879964052314433

In [56]:
np.random.normal(loc=10, scale=100)

34.70955924344875

In [53]:
np.random.normal(0, 1, (3, 5))

array([[-1.36037345, -2.17752387, -0.18071875, -1.14137536, -1.6673638 ],
       [-0.09037666, -0.12645462,  0.67487848,  0.18847641,  0.75658671],
       [-0.267414  ,  0.3533793 , -0.08355021,  0.05846058, -0.68915711]])

In [54]:
np.random.normal?

In [57]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

## Numpy.array的基本操作

In [58]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# 一维转二维
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [60]:
# 几维
x.ndim

1

In [61]:
X.ndim

2

In [62]:
x.shape

(10,)

In [63]:
X.shape

(3, 5)

In [64]:
x.size

10

In [65]:
X.size

15

### numpy.array的数据访问

In [66]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x[0]

0

In [68]:
x[-1]

9

In [72]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
# 不推荐
X[0][0]

0

In [71]:
X[0,0]

0

In [74]:
x[0:5]

array([0, 1, 2, 3, 4])

In [77]:
x[:5]

array([0, 1, 2, 3, 4])

In [78]:
x[5:]

array([5, 6, 7, 8, 9])

In [76]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
x[::2]

array([0, 2, 4, 6, 8])

In [80]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [81]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [82]:
# 等同X[:2]
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [84]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [85]:
X[0]

array([0, 1, 2, 3, 4])

In [86]:
X[0, ::]

array([0, 1, 2, 3, 4])

In [89]:
X[0, :].ndim

1

In [88]:
X[0].ndim

1

In [90]:
X[:, 0]

array([ 0,  5, 10])

In [91]:
# 子矩阵是对原矩阵的引用
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [92]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [93]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [94]:
subX2 = X[:2, :3].copy()
subX2

array([[100,   1,   2],
       [  5,   6,   7]])

In [96]:
subX2[0, 0] = 111
subX2

array([[111,   1,   2],
       [  5,   6,   7]])

In [97]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

### Reshape

In [98]:
x.shape

(10,)

In [99]:
x.ndim

1

In [102]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [103]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
x.ndim

1

In [105]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [106]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [107]:
B.ndim

2

In [108]:
B.shape

(1, 10)

In [109]:
x.shape

(10,)

In [110]:
# 改成10行, 列不考虑
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [111]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [112]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [113]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)