# jupyter notebook高级命令 魔法命令

## %run

In [3]:
%run myscript/hello.py

hello Machine Learning !


## %timeit

In [4]:
%timeit L = [i ** 2 for i in range(1000)]

391 µs ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%timeit L = [i ** 2 for i in range(1000000)]

422 ms ± 12.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

669 µs ± 128 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## %time

In [8]:
%time L = [i ** 2 for i in range(1000)]

CPU times: user 594 µs, sys: 6 µs, total: 600 µs
Wall time: 775 µs


# 其他魔法命令

In [9]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

# numpy.array 基础

In [10]:
import numpy
numpy.__version__

'1.15.1'

In [11]:
import numpy as np

nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
nparr[5]

5

In [13]:
nparr[1] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [14]:
nparr.dtype

dtype('int64')

In [15]:
nparr[3] = 3.14

In [16]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr.dtype

dtype('int64')

In [19]:
nparr3 = np.array([0, 1, 2, 3.0])
nparr3

array([0., 1., 2., 3.])

In [20]:
nparr3.dtype

dtype('float64')